### ISSUE TITLE
Add/Combine/Update all jrpc spec to the README.

### ISSUE THREAD

**Issue by john-g-g** [steemit/yo#28]
Some of it buried in  #10 , and there are some examples in the mock data. Let't get everything we have into the README

**Comment by jnordberg** [comment]
@relativityboy @bnchdrff Can you help with this?

**Comment by bnchdrff** [comment]
i'm on it!

**Comment by GarethNelson** [comment]
Further on this, once we're relatively sure we have a solid stable API we should look into autogenerating documentation again.

@sneak please advise on this, it should be possible to script up something that pulls docstrings out of the code and formats it nicely so we can keep the docs always in sync with the code - we can then stick this on steem.io when it's ready

**Comment by GarethNelson** [comment]
Since i've been running through issues and closing where they appear fixed (or at least those labelled with the mvp milestone) and the README now appears to be complete (in terms of having everything there - formatting and other stuff could still be addressed), i'm closing this.

Please reopen if appropriate.
